name: 'Terragrunt Experiments'
on: workflow_dispatch

env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: './terragrunt-docker'
jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Generate authorized_key.json'
        run: echo $AUTHORIZED_KEY ${{ env.tf_working_dir }}/authorized_key.json
        env:
          AUTHORIZED_KEY: ${{ secrets.AUTHORIZED_KEY }}
      - name: 'Terragrunt Init'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_subcommand: 'run-all init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
