name: 'Apply Terragrunt'
on: workflow_dispatch

env:
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: './terragrunt'
jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Generate authorized_key.json'
        run: echo $AUTHORIZED_KEY ${{ env.tf_working_dir }}/authorized_key.json
        env:
          AUTHORIZED_KEY: ${{ secrets.AUTHORIZED_KEY }}
      - name: 'Terragrunt Plan'
        uses: the-commons-project/terragrunt-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          TF_VAR_REGISTRY_ID: ${{ secrects.REGISTRY_ID }}
          TF_VAR_CLOUD_ID: ${{ secrects.CLOUD_ID }}
          TF_VAR_FOLDER_ID: ${{ secrects.FOLDER_ID }}
          TF_VAR_CERTIFICATE_ID: ${{ secrects.CERTIFICATE_ID }}
          TF_VAR_TELEGRAM_TOKEN: ${{ secrects.TELEGRAM_TOKEN }}
          TF_VAR_TELEGRAM_CHAT_ID: ${{ secrects.TELEGRAM_CHAT_ID }}
